### ISSUE TITLE
Appears to only work with Xcode 14.1

### ISSUE THREAD

**Issue by rzulkoski** [RomanEsin/RealmBinary#10]
I believe that the Carthage assets were only built with Xcode 14.1. If I try to build on an older version of Xcode, it complains about the module being built for Swift 5.7.1. To allow for more flexibility, you may need to mimic use the Realm-Swift assets instead of the Carthage assets and organize your release artifacts as pictured near the end of this [post](https://github.com/realm/realm-swift/issues/6898#issuecomment-1002553302).

Alternatively, I may be doing something wrong. In which case, please correct me. 😄

**Comment by rzulkoski** [comment]
Here's the exact message I received:

`❌  /Users/administrator/ado_agents/agent_1/_work/1/s/iOS/btMobileApp/SwiftPackages/Sources/BTPersistence/Database/Array+List.swift:9:8: module compiled with Swift 5.7.1 cannot be imported by the Swift 5.7 compiler: /Users/administrator/ado_agents/agent_1/_work/1/s/iOS/btMobileApp/DerivedData/Build/Products/Debug-iphonesimulator/RealmSwift.framework/Modules/RealmSwift.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
`

**Comment by RomanEsin** [comment]
Right, should've mentioned it. I'll take a look when I have some free time, thanks for making an issue about this
